In [1]:
#import numpy
import numpy as np

In [2]:
#define variables
A = np.array( [[2, 1, 1],
               [1, 3, 2],
               [1, 0, 0]] )
B = np.array( [4, 5, 6] )

In [3]:
print( np.linalg.solve( A, B ) )

[  6.  15. -23.]


In [4]:
#Lower upper decomposition
#import linear algebra package from scipy
import scipy.linalg as linalg
import numpy as np

In [5]:
A1 = np.array( [[2., 1., 1.],
               [1., 3., 2.],
               [1., 0., 0.]] )
B1 = np.array( [4., 5., 6.] )

In [6]:
LU = linalg.lu_factor( A1 )
x = linalg.lu_solve( LU, B1 )

In [7]:
print( x )

[  6.  15. -23.]


In [8]:
#cholesky decomposition with numpy
import numpy as np

In [10]:
P = np.array( [[10., -1., 2., 0.],
              [-1., 11., -1., 3.],
              [2., -1., 10., -1.],
              [0.0, 3., -1., 8.]]
            )
Q = np.array([6., 25., -11., 15.])

In [11]:
L = np.linalg.cholesky(P)

In [12]:
print(L)

[[ 3.16227766  0.          0.          0.        ]
 [-0.31622777  3.3015148   0.          0.        ]
 [ 0.63245553 -0.24231301  3.08889696  0.        ]
 [ 0.          0.9086738  -0.25245792  2.6665665 ]]


In [13]:
print(np.dot( L, L.T.conj() ))

[[10. -1.  2.  0.]
 [-1. 11. -1.  3.]
 [ 2. -1. 10. -1.]
 [ 0.  3. -1.  8.]]
